### ISSUE TITLE
IOS夜间模式下板块是黑的//

### ISSUE THREAD

**Issue by aik2mlj** [oscardhc/Forum#1]
先喊一句hcgg nb！
如图
![](https://ftp.bmp.ovh/imgs/2020/12/95714b83dbdcf7c9.jpg)

**Comment by oscardhc** [comment]
你可能是在打开App后切换至深色模式吗？目前这个选择栏目的颜色暂时还不能动态调整。
重新打开一遍后问题应该会解决。

**Comment by aik2mlj** [comment]
哦哦是的，没事了
